
# Assignment 3 for Course 1MS041
Make sure you pass the `# ... Test` cells and
 submit your solution notebook in the corresponding assignment on the course website. You can submit multiple times before the deadline and your highest score will be used.

---
## Assignment 3, PROBLEM 1
Maximum Points = 8


Download the updated data folder from the course github website or just download directly the file [https://github.com/datascience-intro/1MS041-2024/blob/main/notebooks/data/smhi.csv](https://github.com/datascience-intro/1MS041-2024/blob/main/notebooks/data/smhi.csv) from the github website and put it inside your data folder, i.e. you want the path `data/smhi.csv`. The data was aquired from SMHI (Swedish Meteorological and Hydrological Institute) and constitutes per hour measurements of wind in the Uppsala Aut station. The data consists of windspeed and direction. Your goal is to load the data and work with it a bit. The code you produce should load the file as it is, please do not alter the file as the autograder will only have access to the original file.

The file information is in Swedish so you need to use some translation service, for instance `Google translate` or ChatGPT.

1. [2p] Load the file, for instance using the `csv` package. Put the wind-direction as a numpy array and the wind-speed as another numpy array.
2. [2p] Use the wind-direction which is an angle in degrees and convert it into a point on the unit circle. Store the `x_coordinate` as one array and the `y_coordinate` as another. From these coordinates, construct the wind-velocity vector.
3. [2p] Calculate the average wind velocity and convert it back to direction and compare it to just taking average of the wind direction as given in the data-file.
4. [2p] The wind velocity is a $2$-dimensional random variable, calculate the empirical covariance matrix which should be a numpy array of shape (2,2).

For you to wonder about, is it more likely for you to have headwind or not when going to the university in the morning.

In [1]:
#Problem 1 part 1

import csv
import numpy as np

file_path = "data/smhi.csv"

start = "Datum;Tid (UTC);Vindriktning;Kvalitet;Vindhastighet;Kvalitet;;Tidsutsnitt:"

winddir = []
windspeed = []

with open(file_path, "r", encoding="utf-8") as file:
    reader = csv.reader(file, delimiter=";")
    startR = False

    for row in reader:
        if startR:
            winddir.append(float(row[2]))
            windspeed.append(float(row[4]))
        elif start in ";".join(row):
            startR = True

problem1_wind_direction = np.array(winddir)
problem1_wind_speed = np.array(windspeed)

In [2]:
#Problem 1 part 2

wind_rad = np.radians(problem1_wind_direction)
problem1_wind_direction_x_coordinate = np.cos(wind_rad)
problem1_wind_direction_y_coordinate = np.sin(wind_rad)
problem1_wind_velocity_x_coordinate = problem1_wind_direction_x_coordinate * problem1_wind_speed
problem1_wind_velocity_y_coordinate = problem1_wind_direction_y_coordinate * problem1_wind_speed

In [3]:

problem1_average_wind_velocity_x_coordinate = np.mean(problem1_wind_velocity_x_coordinate)
problem1_average_wind_velocity_y_coordinate = np.mean(problem1_wind_velocity_y_coordinate)
problem1_average_wind_velocity_angle_degrees = np.degrees(np.arctan2(problem1_average_wind_velocity_y_coordinate, problem1_average_wind_velocity_x_coordinate))

if (problem1_average_wind_velocity_angle_degrees < 0):
    problem1_average_wind_velocity_angle_degrees = problem1_average_wind_velocity_angle_degrees + 360
problem1_average_wind_direction_angle_degrees = np.mean(problem1_wind_direction)

problem1_same_angle = np.isclose(problem1_average_wind_velocity_angle_degrees, problem1_average_wind_direction_angle_degrees)


In [4]:
wind_velocity_components = np.vstack([problem1_wind_velocity_x_coordinate, problem1_wind_velocity_y_coordinate])
problem1_wind_velocity_covariance_matrix = np.cov(wind_velocity_components)
print(problem1_wind_velocity_covariance_matrix)


[[2.45331787 0.06366291]
 [0.06366291 1.89213988]]


In [5]:
# ASSIGNMENT 3, TEST 1, POINTS 8

Beginning tests for problem 1

---------------------------------
Beginning test for part1
---------------------------------

-----Beginning test------
The wind direction data is correct
-----Ending test---------

-----Beginning test------
The wind speed data is correct
-----Ending test---------

---------------------------------
Beginning test for part2
---------------------------------

-----Beginning test------
The wind direction x coordinate data is correct
-----Ending test---------

-----Beginning test------
The wind direction y coordinate data is correct
-----Ending test---------

-----Beginning test------
The wind velocity x coordinate data is correct
-----Ending test---------

-----Beginning test------
The wind velocity y coordinate data is correct
-----Ending test---------

---------------------------------
Beginning test for part3
---------------------------------

-----Beginning test------
The average wind velocity x coordinate data is correct
-----Ending test---------

-----

---
## Assignment 3, PROBLEM 2
Maximum Points = 8


For this problem you will need the [pandas](https://pandas.pydata.org/) package and the [sklearn](https://scikit-learn.org/stable/) package. Inside the `data` folder from the course website you will find a file called `indoor_train.csv`, this file includes a bunch of positions in (X,Y,Z) and also a location number. The idea is to assign a room number (Location) to the coordinates (X,Y,Z).

1. [2p] Take the data in the file `indoor_train.csv` and load it using pandas into a dataframe `df_train`
2. [3p] From this dataframe `df_train`, create two numpy arrays, one `Xtrain` and `Ytrain`, they should have sizes `(1154,3)` and `(1154,)` respectively. Their `dtype` should be `float64` and `int64` respectively.
3. [3p] Train a Support Vector Classifier, `sklearn.svc.SVC`, on `Xtrain, Ytrain` with `kernel='linear'` and name the trained model `svc_train`.

To mimic how [kaggle](https://www.kaggle.com/) works, the Autograder has access to a hidden test-set and will test your fitted model.

In [6]:
import pandas as pd
df_train = pd.read_csv('data/indoor_train.csv')
print(df_train.head())


   Position X   Position Y  Position Z  Location
0        32.0         15.0         4.4        18
1         8.0         17.0         1.5         9
2         4.0         13.0         4.4        13
3        39.0         16.0         4.4        18
4        34.0         12.0         7.6        15


In [7]:

Xtrain = df_train[['Position X', ' Position Y', 'Position Z']].to_numpy(dtype=np.float64)
Ytrain = df_train['Location'].to_numpy(dtype=np.int64)

print("Xtrain: ", Xtrain)
print("Ytrain: ", Ytrain)

Xtrain:  [[32.  15.   4.4]
 [ 8.  17.   1.5]
 [ 4.  13.   4.4]
 ...
 [ 4.   7.   1.5]
 [21.  19.   1.5]
 [25.  19.   7.6]]
Ytrain:  [18  9 13 ...  2 17 19]


In [8]:

from sklearn.svm import SVC
svc_train = SVC(kernel='linear')
svc_train.fit(Xtrain, Ytrain)



SVC(kernel='linear')

In [9]:
# ASSIGNMENT 3, TEST 2, POINTS 8

Beginning tests for problem 2

-----Beginning test------
Your dataframe has the correct length
-----Ending test---------

-----Beginning test------
Your dataframe has the correct number of colums
-----Ending test---------

-----Beginning test------
Your dataframe has the correct type
-----Ending test---------

-----Beginning test------
Your Xtrain has the correct shape
-----Ending test---------

-----Beginning test------
Your Ytrain has the correct shape
-----Ending test---------

-----Beginning test------
Your Xtrain has the correct type
-----Ending test---------

-----Beginning test------
Your Ytrain has the correct type
-----Ending test---------

-----Beginning test------
Your Xtrain has the correct dtype
-----Ending test---------

-----Beginning test------
Your Ytrain has the correct dtype
-----Ending test---------

-----Beginning test------
Your svc_train has the correct type
-----Ending test---------

-----Beginning test------
Your svc_train has been fitted
-----Ending test------

---
## Assignment 3, PROBLEM 3
Maximum Points = 8


Let us build a proportional model ($\mathbb{P}(Y=1 \mid X) = G(\beta_0+\beta \cdot X)$ where $G$ is the logistic function) for the spam vs not spam data. Here we assume that the features are presence vs not presence of a word, let $X_1,X_2,X_3$ denote the presence (1) or absence (0) of the words $("free", "prize", "win")$.

1. [2p] Load the file `data/spam.csv` and create two numpy arrays, `problem3_X` which has shape **(n_texts,3)** where each feature in `problem3_X` corresponds to $X_1,X_2,X_3$ from above, `problem3_Y` which has shape **(n_texts,)** and consists of a $1$ if the email is spam and $0$ if it is not. Split this data into a train-calibration-test sets where we have the split $40\%$, $20\%$, $40\%$, put this data in the designated variables in the code cell.

2. [2p] Follow the calculation from the lecture notes where we derive the logistic regression and implement the final loss function inside the class `ProportionalSpam`. You can use the `Test` cell to check that it gives the correct value for a test-point.

3. [2p] Train the model `problem3_ps` on the training data. The goal is to calibrate the probabilities output from the model. Start by creating a new variable `problem3_X_pred` (shape `(n_samples,1)`) which consists of the predictions of `problem3_ps` on the calibration dataset. Then train a calibration model using `sklearn.tree.DecisionTreeRegressor`, store this trained model in `problem3_calibrator`. Recall that calibration error is the following for a fixed function $f$
$$
    \sqrt{\mathbb{E}[|\mathbb{E}[Y \mid f(X)] - f(X)|^2]}.
$$

4. [2p] Use the trained model `problem3_ps` and the calibrator `problem3_calibrator` to make final predictions on the testing data, store the prediction in `problem3_final_predictions`. 

In [10]:
from sklearn.model_selection import train_test_split
filepath = "data/spam.csv"
data = pd.read_csv("data/spam.csv", usecols=[0,1], names=["label", "text"], skiprows=1, encoding='latin1')

data["label"] = data["label"].map({"ham": 0, "spam": 1})
keywords = ["free", "prize", "win"]
problem3_X = np.array([[int(keyword in text.lower()) for keyword in keywords] for text in data["text"]])
problem3_Y = data["label"].values
problem3_X_train, X_temp, problem3_Y_train, Y_temp = train_test_split(problem3_X, problem3_Y, test_size=0.6, random_state=42)
problem3_X_calib, problem3_X_test, problem3_Y_calib, problem3_Y_test = train_test_split(X_temp, Y_temp, test_size=2/3, random_state=42)

print(problem3_X_train.shape,problem3_X_calib.shape,problem3_X_test.shape,problem3_Y_train.shape,problem3_Y_calib.shape,problem3_Y_test.shape)

(2228, 3) (1114, 3) (2230, 3) (2228,) (1114,) (2230,)


In [11]:


class ProportionalSpam(object):
    def __init__(self):
        self.coeffs = None
        self.result = None
    
    def loss(self, X, Y, coeffs):
        n = X.shape[0]
        b_0 = coeffs[0]
        b = coeffs[1:]
        Z = 2 * Y - 1
        Tloss = 0
        
        for i in range(n):
            Lcomb = b_0 + np.dot(X[i], b)
            Sloss = np.log(1 + np.exp(-Z[i] * Lcomb))
            Tloss += Sloss
        
        Aloss = Tloss/n
        return Aloss

    def fit(self,X,Y):
        import numpy as np
        from scipy import optimize
        opt_loss = lambda coeffs: self.loss(X,Y,coeffs)
        initial_arguments = np.zeros(shape=X.shape[1]+1)
        self.result = optimize.minimize(opt_loss, initial_arguments,method='cg')
        self.coeffs = self.result.x
    
    def predict(self,X):
        if (self.coeffs is not None):
            G = lambda x: np.exp(x)/(1+np.exp(x))
            return np.round(10*G(np.dot(X,self.coeffs[1:])+self.coeffs[0]))/10

In [12]:
from sklearn.tree import DecisionTreeRegressor
problem3_ps = ProportionalSpam()
problem3_ps.fit(problem3_X_train, problem3_Y_train)
problem3_X_pred = problem3_ps.predict(problem3_X_calib).reshape(-1, 1)
problem3_calibrator = DecisionTreeRegressor(max_depth=3, random_state=42)
problem3_calibrator.fit(problem3_X_pred, problem3_Y_calib)


DecisionTreeRegressor(max_depth=3, random_state=42)

In [13]:


problem3_test_pred = problem3_ps.predict(problem3_X_test).reshape(-1, 1)
problem3_final_predictions = problem3_calibrator.predict(problem3_test_pred)



---
#### Local Test for Assignment 3, PROBLEM 3
Evaluate cell below to make sure your answer is valid.                             You **should not** modify anything in the cell below when evaluating it to do a local test of                             your solution.
You may need to include and evaluate code snippets from lecture notebooks in cells above to make the local test work correctly sometimes (see error messages for clues). This is meant to help you become efficient at recalling materials covered in lectures that relate to this problem. Such local tests will generally not be available in the exam.

In [14]:
try:
    import numpy as np
    test_instance = ProportionalSpam()
    test_loss = test_instance.loss(np.array([[1,0,1],[0,1,1]]),np.array([1,0]),np.array([1.2,0.4,0.3,0.9]))
    assert (np.abs(test_loss-1.2828629432232497) < 1e-6)
    print("Your loss was correct for a test point")
except:
    print("Your loss was not correct on a test point")

Your loss was correct for a test point


In [15]:
# ASSIGNMENT 3, TEST 3, POINTS 8

Beginning tests for problem 3

---------------------------------
Beginning test for part1
---------------------------------

-----Beginning test------
problem3_X has the correct shape
-----Ending test---------

-----Beginning test------
problem3_Y has the correct shape
-----Ending test---------

-----Beginning test------
problem3_X_train has the correct number of features
-----Ending test---------

-----Beginning test------
problem3_X_calib has the correct number of features
-----Ending test---------

-----Beginning test------
problem3_X_test has the correct number of features
-----Ending test---------

-----Beginning test------
problem3_Y_train has the correct shape
-----Ending test---------

-----Beginning test------
problem3_Y_calib has the correct shape
-----Ending test---------

-----Beginning test------
problem3_Y_test has the correct shape
-----Ending test---------

---------------------------------
Beginning test for part2
---------------------------------

-----Beginning test-

The number of points you have scored in total for this entire set of Problems is 24 out of 24.